(function (){var h=!0,i=null,j=!1,aa=encodeURIComponent,l=window,m=Error,ba=parseInt,n=document,p=Array;function q(a,c){return a.innerHTML=c}function ca(a,c){return a.currentTarget=c}function da(a,c){return a.length=c}function ea(a,c){return a.className=c}
var r="appendChild",t="push",v="slice",w="replace",x="indexOf",fa="createElement",y="firstChild",ga="setAttribute",z="type",ha="substr",ia="toString",A="length",ja="propertyIsEnumerable",ka="title",B="prototype",C="split",la="location",D="call",ma="href",F="apply",G="join",na="alternate",H;var I=this;function oa(){}function pa(a){a.B=function(){return a.na||(a.na=new a)}}
function qa(a){var c=typeof a;if("object"==c)if(a){if(a instanceof p)return"array";if(a instanceof Object)return c;var b=Object[B][ia][D](a);if("[object Window]"==b)return"object";if("[object Array]"==b||"number"==typeof a[A]&&"undefined"!=typeof a.splice&&"undefined"!=typeof a[ja]&&!a[ja]("splice"))return"array";if("[object Function]"==b||"undefined"!=typeof a[D]&&"undefined"!=typeof a[ja]&&!a[ja]("call"))return"function"}else return"null";else if("function"==c&&"undefined"==typeof a[D])return"object";
return c}function ra(a){var c=qa(a);return"array"==c||"object"==c&&"number"==typeof a[A]}function J(a){return"string"==typeof a}function sa(a){return"function"==qa(a)}function ta(a){var c=typeof a;return"object"==c&&a!=i||"function"==c}function ua(a){return a[va]||(a[va]=++wa)}var va="closure_uid_"+Math.floor(2147483648*Math.random())[ia](36),wa=0;function xa(a,c){var b=p[B][v][D](arguments,1);return function(){var d=p[B][v][D](arguments);d.unshift[F](d,b);return a[F](this,d)}}
function K(a,c){function b(){}b.prototype=c[B];a.m=c[B];a.prototype=new b;a[B].constructor=a}var ya=/^[a-zA-Z0-9\-_.!~*'()]*$/;function za(a){a=""+a;return!ya.test(a)?aa(a):a}function Aa(a,c){if(c)return a[w](Ba,"&amp;")[w](Ca,"&lt;")[w](Da,"&gt;")[w](Ea,"&quot;");if(!Fa.test(a))return a;-1!=a[x]("&")&&(a=a[w](Ba,"&amp;"));-1!=a[x]("<")&&(a=a[w](Ca,"&lt;"));-1!=a[x](">")&&(a=a[w](Da,"&gt;"));-1!=a[x]('"')&&(a=a[w](Ea,"&quot;"));return a}var Ba=/&/g,Ca=/</g,Da=/>/g,Ea=/\"/g,Fa=/[&<>\"]/;
function Ga(a){var c={"&amp;":"&","&lt;":"<","&gt;":">","&quot;":'"'},b=n[fa]("div");return a[w](Ha,function(d,f){var e=c[d];if(e)return e;if("#"==f.charAt(0)){var g=Number("0"+f[ha](1));isNaN(g)||(e=String.fromCharCode(g))}e||(q(b,d+" "),e=b[y].nodeValue[v](0,-1));return c[d]=e})}
function Ia(a){return a[w](/&([^;]+);/g,function(c,b){switch(b){case "amp":return"&";case "lt":return"<";case "gt":return">";case "quot":return'"';default:if("#"==b.charAt(0)){var d=Number("0"+b[ha](1));if(!isNaN(d))return String.fromCharCode(d)}return c}})}
var Ha=/&([^;\s<&]+);?/g,L=p[B],Ja=L[x]?function(a,c,b){return L[x][D](a,c,b)}:function(a,c,b){b=b==i?0:0>b?Math.max(0,a[A]+b):b;if(J(a))return!J(c)||1!=c[A]?-1:a[x](c,b);for(;b<a[A];b++)if(b in a&&a[b]===c)return b;return-1},Ka=L.forEach?function(a,c,b){L.forEach[D](a,c,b)}:function(a,c,b){for(var d=a[A],f=J(a)?a[C](""):a,e=0;e<d;e++)e in f&&c[D](b,f[e],e,a)},La=L.filter?function(a,c,b){return L.filter[D](a,c,b)}:function(a,c,b){for(var d=a[A],f=[],e=0,g=J(a)?a[C](""):a,k=0;k<d;k++)if(k in g){var o=
g[k];c[D](b,o,k,a)&&(f[e++]=o)}return f},Ma=L.every?function(a,c,b){return L.every[D](a,c,b)}:function(a,c,b){for(var d=a[A],f=J(a)?a[C](""):a,e=0;e<d;e++)if(e in f&&!c[D](b,f[e],e,a))return j;return h};function M(a,c){return 0<=Ja(a,c)}function Na(a,c){var b=Ja(a,c),d;(d=0<=b)&&L.splice[D](a,b,1);return d}function Oa(a){return L.concat[F](L,arguments)}function Pa(a){if("array"==qa(a))return Oa(a);for(var c=[],b=0,d=a[A];b<d;b++)c[b]=a[b];return c}
function Qa(a,c,b){return 2>=arguments[A]?L[v][D](a,c):L[v][D](a,c,b)}var Ra;function Sa(a){a=a.className;return J(a)&&a.match(/\S+/g)||[]}function Ta(a,c){for(var b=Sa(a),d=Qa(arguments,1),f=b[A]+d[A],e=b,g=0;g<d[A];g++)M(e,d[g])||e[t](d[g]);ea(a,b[G](" "));return b[A]==f}function Ua(a,c){var b=Sa(a),d=Qa(arguments,1),f=Va(b,d);ea(a,f[G](" "));return f[A]==b[A]-d[A]}function Va(a,c){return La(a,function(b){return!M(c,b)})}function Wa(a,c,b){for(var d in a)c[D](b,a[d],d,a)}var Xa="constructor,hasOwnProperty,isPrototypeOf,propertyIsEnumerable,toLocaleString,toString,valueOf".split(",");
function Ya(a,c){for(var b,d,f=1;f<arguments[A];f++){d=arguments[f];for(b in d)a[b]=d[b];for(var e=0;e<Xa[A];e++)b=Xa[e],Object[B].hasOwnProperty[D](d,b)&&(a[b]=d[b])}}var N,Za,$a,ab;function bb(){return I.navigator?I.navigator.userAgent:i}ab=$a=Za=N=j;var cb;if(cb=bb()){var db=I.navigator;N=0==cb[x]("Opera");Za=!N&&-1!=cb[x]("MSIE");$a=!N&&-1!=cb[x]("WebKit");ab=!N&&!$a&&"Gecko"==db.product}var eb=N,O=Za,fb=ab,gb=$a,hb;
a:{var ib="",jb;if(eb&&I.opera)var kb=I.opera.version,ib="function"==typeof kb?kb():kb;else if(fb?jb=/rv\:([^\);]+)(\)|;)/:O?jb=/MSIE\s+([^\);]+)(\)|;)/:gb&&(jb=/WebKit\/(\S+)/),jb)var lb=jb.exec(bb()),ib=lb?lb[1]:"";if(O){var mb,nb=I.document;mb=nb?nb.documentMode:void 0;if(mb>parseFloat(ib)){hb=""+mb;break a}}hb=ib}var ob=hb,pb={};
function P(a){var c;if(!(c=pb[a])){c=0;for(var b=(""+ob)[w](/^[\s\xa0]+|[\s\xa0]+$/g,"")[C]("."),d=(""+a)[w](/^[\s\xa0]+|[\s\xa0]+$/g,"")[C]("."),f=Math.max(b[A],d[A]),e=0;0==c&&e<f;e++){var g=b[e]||"",k=d[e]||"",o=RegExp("(\\d*)(\\D*)","g"),u=RegExp("(\\d*)(\\D*)","g");do{var s=o.exec(g)||["","",""],E=u.exec(k)||["","",""];if(0==s[0][A]&&0==E[0][A])break;c=((0==s[1][A]?0:ba(s[1],10))<(0==E[1][A]?0:ba(E[1],10))?-1:(0==s[1][A]?0:ba(s[1],10))>(0==E[1][A]?0:ba(E[1],10))?1:0)||((0==s[2][A])<(0==E[2][A])?
-1:(0==s[2][A])>(0==E[2][A])?1:0)||(s[2]<E[2]?-1:s[2]>E[2]?1:0)}while(0==c)}c=pb[a]=0<=c}return c}var qb={};function rb(a){return qb[a]||(qb[a]=O&&!!n.documentMode&&n.documentMode>=a)}!O||rb(9);!O||rb(9);O&&P("8");!gb||P("528");fb&&P("1.9b")||O&&P("8")||eb&&P("9.5")||gb&&P("528");fb&&!P("8")||O&&P("9");function sb(){}sb[B].ha=j;function Q(a,c){this.type=a;this.target=c;ca(this,this.target)}K(Q,sb);Q[B].S=j;Q[B].U=h;var tb={},R={},ub={},vb={};
function wb(a,c,b,d,f){if("array"==qa(c)){for(var e=0;e<c[A];e++)wb(a,c[e],b,d,f);return i}d=!!d;a:{e=R;if(c in e&&(e=e[c],d in e&&(e=e[d],a=ua(a),e[a]))){a=e[a];break a}a=i}if(!a)return j;for(e=0;e<a[A];e++)if(a[e].Ja==b&&a[e].fa==d&&a[e].Ia==f)return xb(a[e].key);return j}
function xb(a){if(!tb[a])return j;var c=tb[a];if(c.T)return j;var b=c.src,d=c[z],f=c.za,e=c.fa;b.removeEventListener?(b==I||!b.ga)&&b.removeEventListener(d,f,e):b.detachEvent&&b.detachEvent(d in vb?vb[d]:vb[d]="on"+d,f);b=ua(b);f=R[d][e][b];if(ub[b]){var g=ub[b];Na(g,c);0==g[A]&&delete ub[b]}c.T=h;f.ba=h;yb(d,e,b,f);delete tb[a];return h}
function yb(a,c,b,d){if(!d.J&&d.ba){for(var f=0,e=0;f<d[A];f++)d[f].T?d[f].za.src=i:(f!=e&&(d[e]=d[f]),e++);da(d,e);d.ba=j;0==e&&(delete R[a][c][b],R[a][c].A--,0==R[a][c].A&&(delete R[a][c],R[a].A--),0==R[a].A&&delete R[a])}}function zb(a,c,b,d,f){var e=1,c=ua(c);if(a[c]){a.C--;a=a[c];a.J?a.J++:a.J=1;try{for(var g=a[A],k=0;k<g;k++){var o=a[k];if(o&&!o.T){var u=e,s=o,E=s.handleEvent(f);s.Ha&&xb(s.key);e=u&E!==j}}}finally{a.J--,yb(b,d,c,a)}}return Boolean(e)}var Ab=0;
function Bb(a){if(a[1]){var c=a[0],b=c[x]("#");0<=b&&(a[t](c[ha](b)),a[0]=c=c[ha](0,b));b=c[x]("?");0>b?a[1]="?":b==c[A]-1&&(a[1]=void 0)}return a[G]("")}var Cb=/#|$/,Db=!O||rb(9);!fb&&!O||O&&rb(9)||fb&&P("1.9.1");O&&P("9");function Eb(a,c){Wa(c,function(b,d){"style"==d?a.style.cssText=b:"class"==d?ea(a,b):"for"==d?a.htmlFor=b:d in Fb?a[ga](Fb[d],b):0==d.lastIndexOf("aria-",0)?a[ga](d,b):a[d]=b})}
var Fb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",rowspan:"rowSpan",valign:"vAlign",height:"height",width:"width",usemap:"useMap",frameborder:"frameBorder",maxlength:"maxLength",type:"type"};function Gb(a,c,b,d){function f(g){g&&c[r](J(g)?a.createTextNode(g):g)}for(;d<b[A];d++){var e=b[d];ra(e)&&!(ta(e)&&0<e.nodeType)?Ka(Hb(e)?Pa(e):e,f):f(e)}}
function S(a,c,b){var d=arguments,f=d[0],e=d[1];if(!Db&&e&&(e.name||e[z])){f=["<",f];e.name&&f[t](' name="',Aa(e.name),'"');if(e[z]){f[t](' type="',Aa(e[z]),'"');var g={};Ya(g,e);e=g;delete e[z]}f[t](">");f=f[G]("")}f=n[fa](f);e&&(J(e)?ea(f,e):"array"==qa(e)?Ta[F](i,[f].concat(e)):Eb(f,e));2<d[A]&&Gb(n,f,d,2);return f}function Hb(a){if(a&&"number"==typeof a[A]){if(ta(a))return"function"==typeof a.item||"string"==typeof a.item;if(sa(a))return"function"==typeof a.item}return j}
function Ib(a){this.O=a||I.document||n}H=Ib[B];H.v=function(a){return J(a)?this.O.getElementById(a):a};H.createElement=function(a){return this.O[fa](a)};H.createTextNode=function(a){return this.O.createTextNode(a)};H.appendChild=function(a,c){a[r](c)};H.append=function(a,c){Gb(9==a.nodeType?a:a.ownerDocument||a.document,a,arguments,1)};function Jb(){}K(Jb,sb);H=Jb[B];H.ga=h;H.Q=i;H.V=function(a){this.Q=a};H.removeEventListener=function(a,c,b,d){wb(this,a,c,b,d)};
H.dispatchEvent=function(a){var c=a[z]||a,b=R;if(c in b){if(J(a))a=new Q(a,this);else if(a instanceof Q)a.target=a.target||this;else{var d=a,a=new Q(c,this);Ya(a,d)}var d=1,f,b=b[c],c=h in b,e;if(c){f=[];for(e=this;e;e=e.Q)f[t](e);e=b[h];e.C=e.A;for(var g=f[A]-1;!a.S&&0<=g&&e.C;g--)ca(a,f[g]),d&=zb(e,f[g],a[z],h,a)&&a.U!=j}if(j in b)if(e=b[j],e.C=e.A,c)for(g=0;!a.S&&g<f[A]&&e.C;g++)ca(a,f[g]),d&=zb(e,f[g],a[z],j,a)&&a.U!=j;else for(f=this;!a.S&&f&&e.C;f=f.Q)ca(a,f),d&=zb(e,f,a[z],j,a)&&a.U!=j;a=Boolean(d)}else a=
h;return a};function Kb(){}pa(Kb);Kb[B].ya=0;Kb.B();function T(a){a||Ra||(Ra=new Ib)}K(T,Jb);H=T[B];H.ma=Kb.B();function Lb(a,c){switch(a){case 1:return c?"disable":"enable";case 2:return c?"highlight":"unhighlight";case 4:return c?"activate":"deactivate";case 8:return c?"select":"unselect";case 16:return c?"check":"uncheck";case 32:return c?"focus":"blur";case 64:return c?"open":"close"}throw m("Invalid component state");}H.Z=i;H.$=j;H.u=i;H.R=i;H.N=i;H.G=i;
H.getId=function(){return this.Z||(this.Z=":"+(this.ma.ya++)[ia](36))};H.v=function(){return this.u};H.V=function(a){if(this.R&&this.R!=a)throw m("Method not supported");T.m.V[D](this,a)};H.I=function(){Mb(this,function(a){a.$&&a.I()});this.la&&this.la.Ka();this.$=j};function Mb(a,c,b){a.N&&Ka(a.N,c,b)}
H.removeChild=function(a,c){if(a){var b=J(a)?a:a.getId(),a=this.G&&b?(b in this.G?this.G[b]:void 0)||i:i;if(b&&a){var d=this.G;b in d&&delete d[b];Na(this.N,a);c&&(a.I(),a.u&&a.u&&a.u.parentNode&&a.u.parentNode.removeChild(a.u));b=a;if(b==i)throw m("Unable to set parent component");b.R=i;T.m.V[D](b,i)}}if(!a)throw m("Child is not in parent component");return a};Ab++;function U(){}var Nb;pa(U);H=U[B];
H.H=function(a,c,b){if(a=a.v?a.v():a)if(O&&!P("7")){var d=Ob(this,Sa(a),c);d[t](c);xa(b?Ta:Ua,a)[F](i,d)}else b?Ta(a,c):Ua(a,c)};H.da=function(a,c){var b;if(a.F&32&&(b=a.P())){if(!c&&a.j&32){try{b.blur()}catch(d){}a.j&32&&(a.W&4&&a.F&4&&a.setActive(j),a.W&32&&a.F&32&&Pb(a,32,j)&&a.z(32,j))}var f;(f=b.getAttributeNode("tabindex"))&&f.specified?(f=b.tabIndex,f="number"==typeof f&&0<=f&&32768>f):f=j;f!=c&&(c?b.tabIndex=0:(b.tabIndex=-1,b.removeAttribute("tabIndex")))}};
H.z=function(a,c,b){var d=a.v();if(d){var f;this.X||(f=this.Y(),this.X={1:f+"-disabled",2:f+"-hover",4:f+"-active",8:f+"-selected",16:f+"-checked",32:f+"-focused",64:f+"-open"});(f=this.X[c])&&this.H(a,f,b);this.L(d,c,b)}};H.L=function(a,c,b){Nb||(Nb={1:"disabled",8:"selected",16:"checked",64:"expanded"});(c=Nb[c])&&a[ga]("aria-"+c,b)};H.P=function(a){return a.v()};H.Y=function(){return"goog-control"};
function Ob(a,c,b){var d=[];b&&(c=c.concat([b]));Ka([],function(f){Ma(f,xa(M,c))&&(!b||M(f,b))&&d[t](f[G]("_"))});return d}function V(){}K(V,U);pa(V);V[B].L=function(a,c,b){16==c?a[ga]("aria-pressed",b):V.m.L[D](this,a,c,b)};V[B].Y=function(){return"goog-button"};O||gb&&P("525");function Qb(a,c){if(!a)throw m("Invalid class name "+a);if(!sa(c))throw m("Invalid decorator function "+c);}var Rb={};
function W(a,c,b){T[D](this,b);if(!(a=c)){for(var a=this.constructor,d;a;){d=ua(a);if(d=Rb[d])break;a=a.m?a.m.constructor:i}a=d?sa(d.B)?d.B():new d:i}this.D=a}K(W,T);H=W[B];H.j=0;H.F=39;H.W=255;H.Ea=0;H.Fa=h;H.g=i;H.P=function(){return this.D.P(this)};H.H=function(a,c){c?a&&(this.g?M(this.g,a)||this.g[t](a):this.g=[a],this.D.H(this,a,h)):a&&this.g&&(Na(this.g,a),0==this.g[A]&&(this.g=i),this.D.H(this,a,j))};
H.I=function(){W.m.I[D](this);this.oa&&this.oa.detach();this.Fa&&!(this.j&1)&&this.D.da(this,j)};H.setActive=function(a){Pb(this,4,a)&&this.z(4,a)};H.z=function(a,c){this.F&a&&c!=!!(this.j&a)&&(this.D.z(this,a,c),this.j=c?this.j|a:this.j&~a)};function Pb(a,c,b){return!!(a.F&c)&&!!(a.j&c)!=b&&(!(a.Ea&c)||a.dispatchEvent(Lb(c,b)))&&!a.ha}if(!sa(W))throw m("Invalid component class "+W);if(!sa(U))throw m("Invalid renderer class "+U);var Sb=ua(W);Rb[Sb]=U;Qb("goog-control",function(){return new W(i)});
function X(){}K(X,V);pa(X);X[B].da=oa;X[B].z=function(a,c,b){X.m.z[D](this,a,c,b);if((a=a.v())&&1==c)a.disabled=b};X[B].L=oa;function Tb(a,c,b){W[D](this,a,c||X.B(),b)}K(Tb,W);Qb("goog-button",function(){return new Tb(i)});O&&P(8);var Ub;(Ub="ScriptEngine"in I&&"JScript"==I.ScriptEngine())&&(I.ScriptEngineMajorVersion(),I.ScriptEngineMinorVersion(),I.ScriptEngineBuildVersion());function Y(a,c){this.a=Ub?[]:"";a!=i&&this.append[F](this,arguments)}
Ub?(Y[B].M=0,Y[B].append=function(a,c,b){c==i?this.a[this.M++]=a:(this.a[t][F](this.a,arguments),this.M=this.a[A]);return this}):Y[B].append=function(a,c,b){this.a+=a;if(c!=i)for(var d=1;d<arguments[A];d++)this.a+=arguments[d];return this};Y[B].clear=function(){Ub?(da(this.a,0),this.M=0):this.a=""};Y[B].toString=function(){if(Ub){var a=this.a[G]("");this.clear();a&&this.append(a);return a}return this.a};
function Vb(a,c,b){a=a||n;b=b&&"*"!=b?b.toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(b||c))c=a.querySelectorAll(b+(c?"."+c:""));else if(c&&a.getElementsByClassName)if(a=a.getElementsByClassName(c),b){for(var d={},f=0,e=0,g;g=a[e];e++)b==g.nodeName&&(d[f++]=g);da(d,f);c=d}else c=a;else if(a=a.getElementsByTagName(b||"*"),c){d={};for(e=f=0;g=a[e];e++)b=g.className,"function"==typeof b[C]&&M(b[C](/\s+/),c)&&(d[f++]=g);da(d,f);c=d}else c=a;if(1<=c[A])return c[0];throw m();}
function Wb(a){return n.createTextNode(a)}if(void 0===l._LOGIN_URL){var Xb;l._IS_MULTILOGIN_ENABLED?(Xb=Yb("AddSession",h),Xb+="&Email="+aa(_USER_EMAIL)):Xb=Yb("ServiceLogin",h);_LOGIN_URL=Xb}function Zb(a,c){if(c instanceof p){for(var b=0;b<c[A];b++)a=a[w]("%"+(b+1),c[b]);return a}return a[w]("%1",c)}
var $b=RegExp("<(/s*(blockquote|body|center|dd|dir|div|dl|dt|form|h1|h2|h3|h4|h5|h6|head|html|hr|isindex|li|menu|noframes|ol|p|table|td|th|tr|title|ul)[^>]*|s*br[^>]*)>","gi"),ac=/<[^>]*>/gi,bc=/</g,cc=/>/g;function dc(a,c){if(!a)return"";c&&(a=a[w]($b," "));a=a[w](ac,"");return a[w](bc,"&lt;")[w](cc,"&gt;")}function ec(a,c){if(a[A]<=c)return a;for(var b=a[C](/\s+/),d=[],f=0,e=0;e<b[A]&&f<=c;e++)d[t](b[e]),f+=b[e][A]+(e?1:0);a=d[G](" ");e!=b[A]&&(a+="...");return a}var fc={};
function gc(a){if(!(a in fc)){var c=fc,b;b=l[la].search;var d=b.search(Cb),f;b:{f=0;for(var e=a[A];0<=(f=b[x](a,f))&&f<d;){var g=b.charCodeAt(f-1);if(38==g||63==g)if(g=b.charCodeAt(f+e),!g||61==g||38==g||35==g)break b;f+=e+1}f=-1}if(0>f)b=i;else{e=b[x]("&",f);if(0>e||e>d)e=d;f+=a[A]+1;b=decodeURIComponent(b[ha](f,e-f)[w](/\+/g," "))}c[a]=b}return fc[a]}function hc(a){gc("hl")&&(a=Bb([a,"&","hl","=",za("en")]));var c=gc("gl");c&&(a=Bb([a,"&","gl","=",za(c)]));return a}
function Yb(a,c){var b="https://www.google.com/accounts/"+a+"?service=reader&passive=true&nui=1&ltmpl=default";if(c){var d;try{d=l.top[la][ma]}catch(f){d=l[la][ma]}b+="&continue="+aa(d)+"&followup="+aa(d)}return b}
var Z={},ic={blue:{k:"#fff",i:"#bccceb",r:"#090992",o:"#bccceb",l:"#1010c8",f:"#7a7ee0",h:"#e5ecf9",e:"#898de9"},green:{k:"#fff",i:"#d8dbbc",r:"#2d8509",o:"#d8dbbc",l:"#58bf2f",f:"#97e07a",h:"#f5fbeb",e:"#adb094"},slate:{k:"#123",i:"#345",r:"#5e805e",o:"#5e6f80",l:"#abc",f:"#5e6f80",h:"#152939",e:"#abc"},gray:{k:"#fff",i:"#ccc",r:"#666",o:"#ccc",l:"#999",f:"#ccc",h:"#eee",e:"#aaa"},khaki:{k:"#f2e9ca",i:"#8e7c6a",r:"#d52",o:"#cba",l:"#543",f:"#ba9",h:"#eae0c6",e:"#987"},pink:{k:"#fff",i:"#aaa",r:"#d69",
o:"#ddd",l:"#e684ad",f:"#ebc",h:"#fcf0f7",e:"#a88"},black:{k:"#000",i:"#aaa",r:"#ccc",o:"#d8dbbc",l:"#d52",f:"#7a2b0e",h:"#111",e:"#999"}},jc={margin:0,padding:0,background:"transparent none",border:"none",textAlign:"left",textIndent:"0",textDecoration:"none",fontWeight:"normal"};
function kc(a,c){var b=lc(a);$(a,b.xa,c);if(a.ea){var d=S("h3");$(a,b.wa,d);d[r](Wb(a.ea));c[r](d)}d=S("ul");$(a,b.va,d);for(var f=0,e;e=a.d.items[f];f++)if(e[na]){var g=S("li");$(a,b.ua,g);var k=S("a",{href:e[na][ma],title:e[ka],"class":"i"});$(a,b.ra,k);var o=dc(e[ka]||e.content);/^[\s\xa0]*$/.test(o==i?"":""+o)||(o=ec(o,48));k[r](Wb(o));g[r](k);if(a.Ca&&!a.aa&&e.origin[ka]){var u=e.origin,k=S("div",{"class":"s"});$(a,b.ta,k);g[r](k);o=u[ka];48<o[A]&&(o=o.substring(0,48));q(k,Zb("from <a>%1</a>",
o));u.htmlUrl&&(u=S("a",{href:u.htmlUrl}),q(u,o),$(a,b.sa,u),k.replaceChild(u,k.getElementsByTagName("a")[0]))}if(a.Ba&&!a.aa){k="";e=e.annotations||[];for(o=0;u=e[o];o++)if(-1!=a.d.id[x](u.userId)&&0<u.content[A]){k=u.content;break}0<k[A]&&(e=S("div"),$(a,b.qa,e),48<k[A]&&(k=k.substring(0,48)),q(e,'"'+k+'"'),g[r](e))}d[r](g)}c[r](d);d=S("div",{"class":"f"});$(a,b.ka,d);a.Da&&(f=S("a",{href:"http://www.google.com/webelements"}),$(a,b.Ga,f),d[r](f));if(a.d.id&&(f=-1!=a.d.id.search(/^user\/(\d+)\/bundle\//),
g=0==a.d.id.lastIndexOf("feed/",0),e=a.d[na]&&a.d[na][ma],!g||f||e))if(e=S("a"),$(a,b.e,e),e[r](Wb("document"in I?Ga("View all &raquo;"):Ia("View all &raquo;"))),f){var s=hc("http://www.google.com/reader/bundle/"+a.d.id),f=mc({pa:s,Aa:"Preview &raquo;"});d[r](f);$(a,b.ja,Vb(f,"gr-bundle-table"));$(a,b.ia,Vb(f,"gr-show-all"));Vb(f,"gr-subscribe-button").onclick=function(){l[la].href=s}}else e.href=g?a.d[na][ma]:hc("http://www.google.com/reader/shared/"+a.d.id),d[r](e);c[r](d)}
function lc(a){if("-"==a.ca)return{};a=ic[a.ca];return{xa:{fontFamily:"arial, sans-serif",fontSize:"10pt",background:a.k,border:"solid 1px "+a.i,margin:"0.5em"},wa:{padding:"0.2em 0.5em",background:a.h,borderBottom:"solid 1px "+a.o,color:a.r},va:{padding:"0.2em",margin:"0 0.5em",overflow:"hidden"},ua:{listStyleType:"none",padding:"0.4em 0 0.4em 0"},ra:{color:a.l,borderBottom:"solid 1px "+a.f},ta:{color:a.f},sa:{color:a.f},qa:{color:"#777",fontStyle:"italic"},ka:{textAlign:"right",borderTop:"solid 1px "+
a.i,background:a.h,padding:"0.2em 8px",fontSize:"small",whiteSpace:"nowrap",overflow:"hidden"},e:{color:a.e,textDecoration:"underline"},ja:{width:"100%"},ia:{textAlign:"right"},Ga:{cssFloat:"left",styleFloat:"left",display:"block",width:"130px",height:"20px",background:O&&7>ob?"none":"url(http://www.google.com/reader/ui/web-elements-logo.png)",filter:"progid:DXImageTransform.Microsoft.AlphaImageLoader(src=http://www.google.com/reader/ui/web-elements-logo.png,sizingMethod=crop)"}}}
function $(a,c,b){if(c){for(var d in jc)b.style[d]=jc[d];for(var f in c)b.style[f]=c[f]}}l.GRC_p=function(a){Z=a};
l.GRC=function(a,c){"GRC_c"in l||(l.GRC_c=0);this.K="readerpublishermodule"+l.GRC_c++;this.d=a;this.ca=Z.c;this.ea=Z.t;this.Ca="true"==Z.s;this.aa="true"==Z.b;this.Ba="true"==Z.n;this.Da="true"==Z.w;if(c)q(c,""),c.id=this.K,kc(this,n.getElementById(this.K));else{n.write('<div id="'+this.K+'" class="reader-publisher-module"></div>');var b=this;l.setTimeout(function(){kc(b,n.getElementById(b.K))},0)}};function mc(a,c){var b=c||new Y;b.append('<div><table class="gr-bundle-table"><tr><td><input class="gr-subscribe-button" type="button" value="',"Subscribe",'"></td><td class="gr-show-all"><a href="',Aa(""+a.pa),'">',a.Aa,"</a></td></tr></table></div>");if(!c){var d=b[ia](),b=n[fa]("div");O?(q(b,"<br>"+d),b.removeChild(b[y])):q(b,d);if(1==b.childNodes[A])b=b.removeChild(b[y]);else{for(d=n.createDocumentFragment();b[y];)d[r](b[y]);b=d}return b}};})();