grep "catego.*movie" 12-macacos-s01-e0103.md
grep "catego.*movie" 3-perc-conto-com-spoilers-de-uma-serie-para-bandidos.md
grep "catego.*movie" 3-perc.md
grep "catego.*movie" a-filosofia-de-rick-and-morty.md
grep "catego.*movie" american-horror-story-s01-murder-house.md
grep "catego.*movie" american-horror-story-s02-asylum.md
grep "catego.*movie" american-horror-story-s03-coven.md
grep "catego.*movie" american-horror-story-s04-freak-show.md
grep "catego.*movie" angel-beats.md
grep "catego.*movie" atypical.md
grep "catego.*movie" better-call-saul-s01.md
grep "catego.*movie" better-call-saul-s02.md
grep "catego.*movie" better-call-saul-terceira-temporada.md
grep "catego.*movie" black-mirror-s01e01-the-national-anthem.md
grep "catego.*movie" black-mirror-s01e02-fifteen-million-merits.md
grep "catego.*movie" black-mirror-s01e03-the-entire-history-of-you.md
grep "catego.*movie" black-mirror-s02e01-be-right-back.md
grep "catego.*movie" black-mirror-s02e02-white-bear.md
grep "catego.*movie" black-mirror-s02e03-the-waldo-moment.md
grep "catego.*movie" black-mirror-s03-white-christmas.md
grep "catego.*movie" blacklist.md
grep "catego.*movie" blue-exorcist.md
grep "catego.*movie" breaking-bad-conclusao.md
grep "catego.*movie" breaking-bad-s01.md
grep "catego.*movie" breaking-bad-s02.md
grep "catego.*movie" breaking-bad-s03.md
grep "catego.*movie" breaking-bad-s04.md
grep "catego.*movie" breaking-bad-s05.md
grep "catego.*movie" cara-gente-branca.md
grep "catego.*movie" chefs-table.md
grep "catego.*movie" cosmos-uma-odisseia-no-espaco-tempo.md
grep "catego.*movie" crashing.md
grep "catego.*movie" death-note.md
grep "catego.*movie" derek.md
grep "catego.*movie" dexter-s07.md
grep "catego.*movie" dexter-s08-final.md
grep "catego.*movie" diario-de-um-jovem-medico.md
grep "catego.*movie" dirk-gentlys-holistic-detective-agency.md
grep "catego.*movie" disk-gentlys-s01.md
grep "catego.*movie" easy.md
grep "catego.*movie" elementary.md
grep "catego.*movie" f-is-for-family-s02.md
grep "catego.*movie" f-is-for-family.md
grep "catego.*movie" family-guy.md
grep "catego.*movie" filosofia-de-mr-robot.md
grep "catego.*movie" fringe.md
grep "catego.*movie" ghost-round.md
grep "catego.*movie" girlboss.md
grep "catego.*movie" glow.md
grep "catego.*movie" haters-back-off.md
grep "catego.*movie" house-of-cards-s05-e01.md
grep "catego.*movie" house-of-cards-s05.md
grep "catego.*movie" house-of-cards-season01.md
grep "catego.*movie" house-of-cards-season02.md
grep "catego.*movie" house-of-cards-season03.md
grep "catego.*movie" house-of-cards-season04.md
grep "catego.*movie" how-to-get-away-with-murder.md
grep "catego.*movie" jessica-jones.md
grep "catego.*movie" kill-la-kill.md
grep "catego.*movie" louie.md
grep "catego.*movie" love-primeira-temporada.md
grep "catego.*movie" luke-cage.md
grep "catego.*movie" madoka-magica.md
grep "catego.*movie" mais-um-verao-americano.md
grep "catego.*movie" making-a-murderer.md
grep "catego.*movie" metastasis.md
grep "catego.*movie" modern-family.md
grep "catego.*movie" mr-robot.md
grep "catego.*movie" narcos.md
grep "catego.*movie" o-incrivel-mundo-de-gumball.md
grep "catego.*movie" one-punch-man-wanpanman.md
grep "catego.*movie" orange-is-the-new-black-s02.md
grep "catego.*movie" orange-is-the-new-black-s03.md
grep "catego.*movie" outlander-primeira-temporada.md
grep "catego.*movie" outlander-segunda-temporada.md
grep "catego.*movie" peppa-pig.md
grep "catego.*movie" regular-show.md
grep "catego.*movie" rick-and-morty-primeira-temporada.md
grep "catego.*movie" saco-de-ossos.md
grep "catego.*movie" samurai-gourmet.md
grep "catego.*movie" science-of-star-wars.md
grep "catego.*movie" sense8-segunda-temporada.md
grep "catego.*movie" sense8.md
grep "catego.*movie" sherlock-s03.md
grep "catego.*movie" sherlocks-s04e01.md
grep "catego.*movie" south-park-season20-ep-1-4.md
grep "catego.*movie" south-park.md
grep "catego.*movie" steins-gate.md
grep "catego.*movie" stranger-things.md
grep "catego.*movie" street-fighter-assassins-fist.md
grep "catego.*movie" supergirl-2015.md
grep "catego.*movie" sword-art-online-s01.md
grep "catego.*movie" sword-art-online-s02.md
grep "catego.*movie" terror-in-resonance.md
grep "catego.*movie" the-lizzie-borden-chronicles.md
grep "catego.*movie" the-sound-of-your-heart-s01.md
grep "catego.*movie" the-walking-dead-s01.md
grep "catego.*movie" the-walking-dead-s02.md
grep "catego.*movie" the-walking-dead-s03.md
grep "catego.*movie" travelers.md
grep "catego.*movie" true-detective-primeiras-impressoes.md
grep "catego.*movie" ultimate-beastmaster-s01.md
grep "catego.*movie" westworld-s01.md
grep "catego.*movie" westworld-season01-revisited.md
