@echo off
dir /b sample-post.*
dir /b hello-world.*
dir /b a-inteligencia-do-if-parte-1.*
dir /b introducao-ao-debugging-tools-for-windows.*
dir /b disassembling-the-array-operator.*
dir /b historia-do-windows-parte-10.*
dir /b a-inteligencia-do-if-parte-2.*
dir /b introducao-ao-softice.*
dir /b historia-do-windows-parte-20.*
dir /b google-shortcuts.*
dir /b precedence-difference.*
dir /b desejo-insano-de-programar-no-kernel.*
dir /b what-happens-inside-the-sizeof-operator.*
dir /b como-ser-um-melhor-desenvolvedor-nos-proximos-seis-meses.*
dir /b antidebug-interpretacao-baseada-em-excecao-parte-1.*
dir /b c0x-parcial-no-novo-gcc-43.*
dir /b movendo-o-cursor-do-mouse-com-o-teclado.*
dir /b c-and-c-operators-precedence-table.*
dir /b historia-da-linguagem-c-parte-1.*
dir /b historia-do-windows-parte-30.*
dir /b historia-do-windows-parte-351.*
dir /b antidebug-interpretacao-baseada-em-excecao-parte-2.*
dir /b gina-x-credential-provider.*
dir /b historia-da-linguagem-c-parte-2.*
dir /b junctions.*
dir /b erro-de-compilacao-funcoes-muito-novas-na-win32-api.*
dir /b antidebug-ocupando-a-debugport.*
dir /b todolist.*
dir /b hook-de-api-no-windbg.*
dir /b barata-eletrica-e-o-hacker-de-antigamente.*
dir /b historia-do-windows-parte-40.*
dir /b o-passado-torto-de-um-programador-por-acaso.*
dir /b antidebug-detectando-attach.*
dir /b guia-basico-de-controle-de-codigo-source-safe.*
dir /b aquisicao-de-recurso-e-inicializacao.*
dir /b hook-de-com-no-windbg.*
dir /b a-mobilidade-das-variaveis-no-printf.*
dir /b why-is-my-dll-locked.*
dir /b introducao-ao-c-builderturbo-c.*
dir /b developer-you-need-to-know-english.*
dir /b debug-da-bios-com-o-softice-16-bits.*
dir /b cronograma.*
dir /b historia-do-windows-parte-50.*
dir /b engenharia-reversa-para-principiantes.*
dir /b the-c-programming-language.*
dir /b guia-basico-para-programadores-de-primeiro-int-main.*
dir /b por-que-minha-dll-travou.*
dir /b guia-basico-para-programadores-de-primeiro-breakpoint.*
dir /b typeid-e-os-perigos-do-nao-polimorfismo.*
dir /b protecao-dos-membros-protected.*
dir /b brincando-com-o-windbg.*
dir /b desenvolvendo-em-linha-de-comando.*
dir /b ponteiros-de-metodo-conceito-fundamental.*
dir /b ponteiro-de-metodo-qual-this-e-usado.*
dir /b detectando-hooks-globais-no-windbg.*
dir /b mousetool.*
dir /b sdelete.*
dir /b historia-do-windows-parte-51.*
dir /b usando-a-libc-nativa-do-windows.*
dir /b carregando-dlls-arbitrarias-pelo-windbg.*
dir /b carregando-dlls-arbitrarias-pelo-windbg-parte-2.*
dir /b desenhando-em-c-builder.*
dir /b conceitos-basicos-na-programacao-com-c-builder.*
dir /b interacao-entre-controles-no-c-builder.*
dir /b makefiles-e-visual-studio-para-todos.*
dir /b gerenciamento-de-janelas-em-c-builder.*
dir /b debug-remoto-no-c-builder.*
dir /b sizeof-de-novo.*
dir /b drag-and-drop-no-c-builder.*
dir /b banco-de-dados-no-c-builder.*
dir /b o-que-acontece-quando-o-contador-estoura.*
dir /b curiosidades-inuteis-o-operador-de-subscrito-em-c.*
dir /b gambi-do-dia-swap-com-apenas-duas-variaveis.*
dir /b como-ser-um-melhor-desenvolvedor-em-2008.*
dir /b cppcon-iii.*
dir /b como-ter-um-melhor-blogue-em-2008.*
dir /b analisando-dumps-com-windbg-e-ida.*
dir /b temas-no-windbg.*
dir /b encontrando-as-respostas-do-flash-pops.*
dir /b otimizacao-em-funcoes-recursivas.*
dir /b terceiro-encontro-c.*
dir /b keychanger-de-crianca.*
dir /b rmthread-rode-codigo-em-processo-vizinho.*
dir /b compartilhando-variaveis-com-o-mundo.*
dir /b compartilhando-variaveis-com-o-mundo-v2.*
dir /b process-monitor-e-o-monopolio-malcriado.*
dir /b silly-regex-trick-finding-the-project-who-failed-inside-a-vs-big-solution.*
dir /b desconstruindo-ioccc.*
dir /b funky-do-while.*
dir /b os-diferentes-erros-na-linguagem-c.*
dir /b creative-commons.*
dir /b configurando-seus-projetos-no-visual-studio.*
dir /b codigos-de-entrevista-o-ponteiro-nulo.*
dir /b conversor-de-houaiss-para-babylon-parte-1.*
dir /b quando-o-ponteiro-nulo-nao-e-invalido.*
dir /b iteradores-nao-sao-constantes.*
dir /b estranho.*
dir /b sed-grep-e-afins.*
dir /b o-misterio-das-pilhas-diferentes.*
dir /b influence-board.*
dir /b quarto-encontro-c.*
dir /b como-rodar-qualquer-coisa-como-servico.*
dir /b depuracao-da-mbr.*
dir /b windbg-a-distancia.*
dir /b backup-de-pobre.*
dir /b epa-ccpp-4-nossa-comunidade-ganhando-forma.*
dir /b try-catch-flutuante.*
dir /b conversor-de-houaiss-para-babylon-parte-2.*
dir /b linux-e-o-dhcp.*
dir /b aprendendo-assembly-com-o-depurador.*
dir /b guia-basico-de-controle-de-codigo-mercurial.*
dir /b crash-dump-analysis-o-livro.*
dir /b ode-ao-c.*
dir /b csi-crashed-server-investigation.*
dir /b seminario-ccpp-portabilidade-e-performance.*
dir /b bazaar-e-fedora-8-a-saga.*
dir /b acessando-memoria-fisica-no-windbg.*
dir /b read-the-functional-manual.*
dir /b como-tratar-um-merge-no-bazaar.*
dir /b kernel-mode-user-mode.*
dir /b aquele-do-while-engracado.*
dir /b busca-do-google-com-atalhos.*
dir /b mousetool-clique-automatico-do-seu-rato.*
dir /b aprendendo-rapidamente-conceitos-essenciais-do-windbg.*
dir /b how-to-run-anything-as-a-service.*
dir /b como-criar-uma-lib-no-visual-studio.*
dir /b resultado-do-seminario-ccpp.*
dir /b launchpad-e-a-democracia-do-codigo-fonte.*
dir /b declaracao-x-definicao.*
dir /b guia-basico-de-repositorios-no-bazaar.*
dir /b primeiro-ano-do-novo-calonicombr.*
dir /b como-fazer-merge-de-projetos-distintos-no-bazaar.*
dir /b alinhamento-de-memoria-portavel.*
dir /b e-possivel-carregar-duas-dlls-gemeas-no-mesmo-processo.*
dir /b como-estou-trabalhando-com-o-bazaar.*
dir /b primeiros-passos-na-documentacao-de-codigo-fonte-usando-doxygen.*
dir /b reflexao-em-c.*
dir /b pesquisas-sobre-a-gina.*
dir /b virtualbox.*
dir /b projeto-modelo.*
dir /b primeiros-passos-no-vmware-workstation.*
dir /b segunda-versao-do-houaiss2babylon.*
dir /b o-caso-da-funcao-de-delay-load-desaparecida.*
dir /b o-conhecido-unresolved-external.*
dir /b aprenda-a-usar-sua-api.*
dir /b entrevista-com-o-caloni-no-do-zero-ao-mestre.*
dir /b antidebugging-using-exceptions-part-one.*
dir /b antidebugging-using-exceptions-part-two.*
dir /b antidebugging-using-the-debugport.*
dir /b antidebugging-during-the-process-attach.*
dir /b aprendizado-em-kernel-mode.*
dir /b guia-para-iniciantes-no-driverentry.*
dir /b quando-o-navegador-nao-quer-largar-um-arquivo.*
dir /b duas-pequenas-dicas-para-programar-no-caos.*
dir /b os-processos-fantasma.*
dir /b processleaker.*
dir /b de-volta-a-tona.*
dir /b retorno-do-pathisdirectory.*
dir /b todo-programador-e-um-filosofo-em-potencial.*
dir /b reuna-seus-comandos-mais-usados-no-windbg-com-.*tree.*
dir /b v.*
dir /b windows-jobs-com-completion-port.*
dir /b cnasi-geracao-y-e-seus-gastos-em-ti.*
dir /b o-que-acontece-com-um-programador-com-pressa.*
dir /b impressoes-do-quinto-encontro-de-ccpp.*
dir /b como-usar-wtl-com-o-atl-do-ddk.*
dir /b a-alca-dentro-do-fio-gerou-um-bloqueio-da-morte.*
dir /b como-funciona-o-psexec.*
dir /b houaissparababylon-versao-beta.*
dir /b basico-do-basico-ponteiros.*
dir /b basico-do-basico-tipos.*
dir /b basico-do-basico-binario.*
dir /b houaissparababylon-versao-11.*
dir /b basico-do-basico-assembly.*
dir /b as-funcoes-polegar.*
dir /b windbginfo.*
dir /b os-problemas-mais-cabeludos.*
dir /b provas-de-conceito-yes.*
dir /b depurando-ate-o-ultimo-segundo.*
dir /b a-fila-das-threads.*
dir /b deixe-o-programador-programar.*
dir /b a-sala-da-fila-das-threads.*
dir /b ultimas-pesquisas-na-blogosfera-nacional.*
dir /b english-posts.*
dir /b meu-roteiro-c.*
dir /b como-compilar-em-somente-um-passo.*
dir /b programadores-de-verdade-nao-usam-java.*
dir /b strings.*
dir /b polimorfismo-estatico.*
dir /b static-polymorphism.*
dir /b name-mangling.*
dir /b a-procura-de-vida-extraterrestre.*
dir /b cuidado-com-a-copia-de-arquivos-na-vmware.*
dir /b o-que-andei-fazendo-nos-ultimos-10-anos.*
dir /b adplus-no-cliente-nao-voce.*
dir /b what-ive-been-doing-in-the-last-10-years.*
dir /b o-boot-no-windows-sem-windows.*
dir /b o-boot-no-windows-pre-ntldr.*
dir /b o-boot-no-windows-ntldr.*
dir /b o-boot-no-windows-kernel.*
dir /b aprendendo-um-terceiro-idioma.*
dir /b devaneio-nerd-rapido-sobre-aniversarios.*
dir /b devaneio-nerd-rapido-sobre-profecias.*
dir /b importando-tipos-de-outros-projetos.*
dir /b passagem-por-valor-e-emails-com-anexo.*
dir /b house.*
dir /b correcao-de-bugs-instantanea.*
dir /b restauranto-o-registro.*
dir /b bazaar-grafico.*
dir /b convivendo-entre-todolist-e-microsoft-project.*
dir /b novidades-no-windbg-7.*
dir /b houaiss-para-babylon-12.*
dir /b using-todolist-and-microsoft-project-together.*
dir /b typedef-arcaico.*
dir /b por-que-long-pointer.*
dir /b analogicamente-perfeito.*
dir /b modificadores-e-qualificadores-de-tipo.*
dir /b enum.*
dir /b const-e-volatile.*
dir /b breakpoints-promiscuos.*
dir /b setimo-encontro-de-programadores-c.*
dir /b twitter-eu.*
dir /b como-achar-o-codigo-fonte-sem-simbolos.*
dir /b novas-diferencas-no-bazaar.*
dir /b nao-e-minha-culpa.*
dir /b foto-dos-melhores-momentos.*
dir /b evento-c.*
dir /b gerando-dumps-automatizados.*
dir /b como-ofuscar-strings.*
dir /b tres-em-um.*
dir /b atualizando-houaissparababylon-no-saite.*
dir /b formatmessage-para-dumies.*
dir /b entao-voce-ainda-nao-usa-controle-de-fonte.*
dir /b suporte-tecnico.*
dir /b patch-de-emergencia.*
dir /b patch-de-emergencia-2.*
dir /b ii-seminario-portabilidade-e-performance.*
dir /b pos-ii-seminario-portabilidade-e-performance.*
dir /b trabalhando-em-multiplos-ambientes.*
dir /b dependencia-pedindo-carona.*
dir /b reuniao-de-programadores-c-ha-5-anos.*
dir /b esse-ponteiro-vai-ate-onde.*
dir /b atividades-extracurriculares.*
dir /b mudanca.*
dir /b vtable.*
dir /b daytoday.*
dir /b base64.*
dir /b reorganizando-meus-feeds-de-novo.*
dir /b loucuras-multithreading.*
dir /b houaiss-no-kindle.*
dir /b bazaar-com-subversion.*
dir /b houaiss-1-3.*
dir /b sem-reflection.*
dir /b comparando-strings-no-windbg.*
dir /b novo-branch-para-projetos-do-caloni-com-br.*
dir /b cronogramas-baseados-em-fatos-reais.*
dir /b trilha-de-c-organizada-pelo-grupo-cc-brasil.*
dir /b videos-do-boostcon.*
dir /b tdc-2011.*
dir /b e-foi-se-o-tdc.*
dir /b cuidado-com-variaveis-temporarias.*
dir /b depuracao-de-emergencia.*
dir /b oitavo-encontro-do-grupo-cc-brasil.*
dir /b coders-at-work-jamie-zawinski-e-douglas-crockford.*
dir /b coders-at-work-brendan-eich-threads-e-depuracao.*
dir /b depuracao-de-emergencia-receita-de-bolo.*
dir /b vida-e-software.*
dir /b rvalue-e-o-novo-lvalue.*
dir /b conteudo-da-palestra.*
dir /b header-inutil.*
dir /b engenharia-reversa-em-itajuba.*
dir /b coletando-dumps-automaticamente.*
dir /b consumo-abusivo-de-memoria.*
dir /b sobrecarga-de-funcao-as-avessas.*
dir /b problemas-comuns-no-windbg-e-suas-solucoes.*
dir /b meus-repositorios-no-github.*
dir /b novos-atalhos-aprendidos-no-vim.*
dir /b gettickcount-nao-e-um-gerador-de-ids-unicos.*
dir /b minha-palestra-do-tdc-2012.*
dir /b extreme-go-horse.*
dir /b 10-encontro-de-programadores-de-c-c-2.*
dir /b depuracao-na-nuvem.*
dir /b melhor-integracao-entre-vim-e-visual-studio.*
dir /b mais-um-cpp-mvp.*
dir /b ponto-flutuante-afundando.*
dir /b mvp-showcast.*
dir /b uma-nova-linguagem.*
dir /b bovespabacktesting.*
dir /b remove_if-ate-remove-so-que-diferente.*
dir /b real-programmers-dont-use-java.*
dir /b houaiss-para-babylon-em-python.*
dir /b a-moda-agora-e-levar-lambda-na-funcao.*
dir /b lambda-o-retorno.*
dir /b geleia-de-codigo.*
dir /b 2048-motivos-para-nao-programar.*
dir /b que-geleia-de-mocoto.*
dir /b poker-face.*
dir /b 50-anos-de-basic.*
dir /b estruturas-vs-classes-fight.*
dir /b desmontando-o-aulete-digital.*
dir /b ss.*
dir /b eles-querem-que-a-gina-va-embora-tres-posts-sobre-evolucao-windows.*
dir /b dando-cabo-do-windbg.*
dir /b se-iterando-com-os-pseudo-ponteiros-uma-breve-introducao.*
dir /b introducao-a-introducao-a-computacao.*
dir /b tdc-2014.*
dir /b tdc-2014-seguranca.*
dir /b integrando-bitbucketgithub-com-trello.*
dir /b vestindo-a-camisa-da-minha-empresa.*
dir /b o-novo-como-nao-dar-step-into-do-visual-studio-201213.*
dir /b tdc2014-trilha-de-cc-teve-palestras-para-todos-os-gostos.*
dir /b tdc2014-trilhas-de-seguranca-o-que-e-ser-hacker.*
dir /b shareando-ponteiros.*
dir /b houaiss-para.*
dir /b mvp-summit.*
dir /b entendendo-a-compilacao.*
dir /b por-que-o-visual-studio-gera-executaveis-mutantes.*
dir /b rip-alberto.*
dir /b origem-do-tipo-char.*
dir /b 11-encontro-ccpp-brasil-cfp.*
dir /b 11-encontro-ccpp-brasil-inscricoes.*
dir /b guia-alocacao-nos-clientes.*
dir /b os-melhores-eventos-sao-de-programadores-c.*
dir /b convencao-de-chamada.*
dir /b c-cpp-engenharia-reversa-e-todo-o-resto.*
dir /b analisando-erros-pelo-filtro-do-file-mon.*
dir /b depurando-ate-o-fim-do-mundo-e-de-volta-de-novo-source-server-com-github.*
dir /b logs-em-servicos-e-outras-coisas.*
dir /b tdc-sp-2015-cfp.*
dir /b escolha-de-palestras-tdc-2015-sp.*
dir /b tdc-2015-no-more.*
dir /b existem-programadores-ccpp-no-rio-de-janeiro.*
dir /b tecnicas-antidebugging-no-tdc-2015.*
dir /b voce-sabe-o-que-esta-usando-no-seu-codigo.*
dir /b por-que-as-startups-brasileiras-precisam-de-outsourcing.*
dir /b ccppbr-rio-12.*
dir /b o-estranho-caso-do-pdb-mal-formado.*
dir /b e-o-fonte-idiota.*
dir /b fundamentos.*
dir /b indexando-simbolos-com-rapidez.*
dir /b como-ser-um-hacker.*
dir /b classe-objeto-contexto.*
dir /b classe-objeto-contexto-metodo.*
dir /b classe-objeto-contexto-metodo-polimorfismo.*
dir /b gabaritos.*
dir /b templates-em-c-no-lugar-de-macros.*
dir /b a-resolucao-do-bitcoin.*
dir /b log-de-apis-chamadas-direto-do-windbg.*
dir /b exportando-repositorios-antigos-do-bazaar-para-git.*
dir /b nao-atualize-seu-sistema.*
dir /b testando-sistema-de-postagem.*
dir /b rank-and-file-code-jam.*
dir /b cezinha-explica.*
dir /b palestra-stack-overflow.*
dir /b fotos-dos-primeiros-encontros.*
