mv 12-rules-for-life-jordan-b-peterson.md ..\leituras
mv as-portas-da-percepcao.md ..\leituras
mv ayn-rand-sobre-a-essencia-da-feminilidade.md ..\leituras
mv ayn-rand-sobre-a-importancia-da-filosofia.md ..\leituras
mv cafe.md ..\leituras
mv cali-2018.md ..\leituras
mv coders-at-work.md ..\leituras
mv confirmation-theory.md ..\leituras
mv crash-dump-analysis-o-livro.md ..\leituras
mv dialogos-sobre-o-vegetarianismo.md ..\leituras
mv george-orwell-politics-and-the-english-language.md ..\leituras
mv introducao-a-introducao-a-computacao.md ..\leituras
mv jejum-intermitente-e-nutricionistas-em-furia.md ..\leituras
mv just-the-arguments.md ..\leituras
mv listas.md ..\leituras
mv livro-mastering-the-key-to-success-and-long-term-fulfillment.md ..\leituras
mv livro.md ..\leituras
mv lugares.md ..\leituras
mv memento.md ..\leituras
mv native-floripa-2018.md ..\leituras
mv o-mundo-de-sofia.md ..\leituras
mv o-papel-da-genetica-na-mobilidade-social.md ..\leituras
mv o-que-alguem-pode-fazer-para-salvar-o-pais-e-o-mundo-resposta-falar.md ..\leituras
mv on-writing-well.md ..\leituras
mv primacy-of-existence.md ..\leituras
mv queijos.md ..\leituras
mv restaurantes.md ..\leituras
mv salta-2018.md ..\leituras
mv sinais-do-fim.md ..\leituras
mv stanford-encyclopedia-of-philosophy-para-kindle.md ..\leituras
mv terceiro-encontro-c.md ..\leituras
mv the-best-of-edw519.md ..\leituras
mv the-c-programming-language.md ..\leituras
mv why-facts-dont-change-our-minds.md ..\leituras
mv why-people-are-irrational-about-politics.md ..\leituras
