# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cine Tênis Verde
email: cinetenisverde.com.br@gmail.com
description: A melhor forma de ver um filme é com o cérebro.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.cinetenisverde.com.br" # the base hostname & protocol for your site
twitter_username: cinetenisverde
github_username:  cinetenisverde

# Build settings
markdown: kramdown
defaults:
  -
    values:
      layout: "default"
