// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Object.proto

#ifndef PROTOBUF_Object_2eproto__INCLUDED
#define PROTOBUF_Object_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
#include "Property.pb.h"
// @@protoc_insertion_point(includes)

namespace MV {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_Object_2eproto();
void protobuf_AssignDesc_Object_2eproto();
void protobuf_ShutdownFile_Object_2eproto();

class Object;

// ===================================================================

class Object : public ::google::protobuf::Message {
 public:
  Object();
  virtual ~Object();
  
  Object(const Object& from);
  
  inline Object& operator=(const Object& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Object& default_instance();
  
  void Swap(Object* other);
  
  // implements Message ----------------------------------------------
  
  Object* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Object& from);
  void MergeFrom(const Object& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional string Name = 7;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 7;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  
  // repeated .MV.Object Objects = 6;
  inline int objects_size() const;
  inline void clear_objects();
  static const int kObjectsFieldNumber = 6;
  inline const ::MV::Object& objects(int index) const;
  inline ::MV::Object* mutable_objects(int index);
  inline ::MV::Object* add_objects();
  inline const ::google::protobuf::RepeatedPtrField< ::MV::Object >&
      objects() const;
  inline ::google::protobuf::RepeatedPtrField< ::MV::Object >*
      mutable_objects();
  
  // repeated .MV.Property Properties = 5;
  inline int properties_size() const;
  inline void clear_properties();
  static const int kPropertiesFieldNumber = 5;
  inline const ::MV::Property& properties(int index) const;
  inline ::MV::Property* mutable_properties(int index);
  inline ::MV::Property* add_properties();
  inline const ::google::protobuf::RepeatedPtrField< ::MV::Property >&
      properties() const;
  inline ::google::protobuf::RepeatedPtrField< ::MV::Property >*
      mutable_properties();
  
  // @@protoc_insertion_point(class_scope:MV.Object)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* name_;
  ::google::protobuf::RepeatedPtrField< ::MV::Object > objects_;
  ::google::protobuf::RepeatedPtrField< ::MV::Property > properties_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_Object_2eproto();
  friend void protobuf_AssignDesc_Object_2eproto();
  friend void protobuf_ShutdownFile_Object_2eproto();
  
  void InitAsDefaultInstance();
  static Object* default_instance_;
};
// ===================================================================


// ===================================================================

// Object

// optional string Name = 7;
inline bool Object::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Object::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Object::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Object::clear_name() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& Object::name() const {
  return *name_;
}
inline void Object::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void Object::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void Object::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Object::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  return name_;
}
inline ::std::string* Object::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// repeated .MV.Object Objects = 6;
inline int Object::objects_size() const {
  return objects_.size();
}
inline void Object::clear_objects() {
  objects_.Clear();
}
inline const ::MV::Object& Object::objects(int index) const {
  return objects_.Get(index);
}
inline ::MV::Object* Object::mutable_objects(int index) {
  return objects_.Mutable(index);
}
inline ::MV::Object* Object::add_objects() {
  return objects_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::MV::Object >&
Object::objects() const {
  return objects_;
}
inline ::google::protobuf::RepeatedPtrField< ::MV::Object >*
Object::mutable_objects() {
  return &objects_;
}

// repeated .MV.Property Properties = 5;
inline int Object::properties_size() const {
  return properties_.size();
}
inline void Object::clear_properties() {
  properties_.Clear();
}
inline const ::MV::Property& Object::properties(int index) const {
  return properties_.Get(index);
}
inline ::MV::Property* Object::mutable_properties(int index) {
  return properties_.Mutable(index);
}
inline ::MV::Property* Object::add_properties() {
  return properties_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::MV::Property >&
Object::properties() const {
  return properties_;
}
inline ::google::protobuf::RepeatedPtrField< ::MV::Property >*
Object::mutable_properties() {
  return &properties_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace MV

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Object_2eproto__INCLUDED
